---
- hosts: iscsi
  remote_user: cloudadmin
  become: true
  become_user : root
  pre_tasks:
    - include_vars: ./vars/iscsi_storage_profile.yaml

  tasks:
  # tasks sourced from https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-suse-pacemaker

  - name: Remove unneeded packages
    community.general.zypper:
      name: "{{ item }}"
      state: absent
    with_items:
      - lio-utils
      - python-rtslib
      - python-configshell
      - targetcli

  - name: Install required packages
    community.general.zypper:
      name: "{{ item }}"
      state: present
    with_items:
      - targetcli-fb
      - dbus-1-python

  - name: Enable the iscsi target service
    ansible.builtin.systemd:
      name: targetcli
      state: started
      enabled: yes
  
  - name: Prepare iscsi disks
    vars:
      sap_storage_cloud_type: 'generic'
      sap_storage_sap_type: 'sap_hana'
      sap_storage_action: 'prepare'
    include_role: 
      name: ../roles/sap_storage

  - name: Configs HANA SBD target 
    ansible.builtin.command: 
      cmd: "{{ item.command }}" 
      creates: "{{ item.creates }}" 
    with_items: 
      - { 'command': 'targetcli backstores/fileio create sbdhana /srv/sbd/sbdhana 50M write_back=false', 'creates': '/srv/sbd/sbdhana' }
      - { 'command': 'targetcli iscsi/ create iqn.2006-04.dbnw1.local:dbnw1', 'creates': '/sys/kernel/config/target/iscsi/iqn.2006-04.dbnw1.local:dbnw1' }
      - { 'command': 'targetcli iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpg1/luns/ create /backstores/fileio/sbdhana', 'creates': '/sys/kernel/config/target/iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpgt_1/lun/lun_0' }
      - { 'command': 'targetcli iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpg1/acls/ create iqn.2006-04.nw1-db-0.local:nw1-db-0', 'creates': '/sys/kernel/config/target/iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpgt_1/acls/iqn.2006-04.nw1-db-0.local:nw1-db-0' }
      - { 'command': 'targetcli iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpg1/acls/ create iqn.2006-04.nw1-db-1.local:nw1-db-1', 'creates': '/sys/kernel/config/target/iscsi/iqn.2006-04.dbnw1.local:dbnw1/tpgt_1/acls/iqn.2006-04.nw1-db-0.local:nw1-db-1' }


        