---
- hosts: hana
  remote_user: cloudadmin
  become: true
  become_user : root
  vars:
    scale_out: false
    use_sapconf: false
    saptune_solution: HANA
    platform: azure
    cluster_node: true
        
  tasks:

  # Ensure required installation of required packages
    - name: Ensure libssl 2.1 is installed on distributed Systems
      community.general.zypper:
        name: libssh2-1 # Caution, no version control here (yet)
        state: present
      when: scale_out | bool

    # 3018133 - Linux: Running SAP applications compiled with GCC 10.x
    - name: Ensure minimum version of GCC10 are installed
      community.general.zypper:
        name: "{{ item }}"
        state: present
      loop:
        - 'libgcc_s1>=10.2.1'
        - 'libstdc++6>=10.2.1'
        - 'libatomic1>=10.2.1'
    
    - name: Configure sapconf based systems
      ansible.builtin.include_tasks: ./tasks/sapconf.yaml
      when: use_sapconf | bool

    # saptune to be handled here with more included tasks!
    - name: Configure saptune based systems
      ansible.builtin.include_tasks: ./tasks/saptune.yaml
      when: not use_sapconf | bool 
    
  handlers:
    - name: reboot
      ansible.builtin.reboot:

