---
- hosts: hana
  remote_user: "{{ remote_user_to_use }}"
  become: true
  become_user : root
  pre_tasks:
    - include_vars: ./vars/hana_storage_profile.yaml

  tasks:

  - name: HANA storage preperation
    vars:
      sap_storage_cloud_type: 'generic'
      sap_storage_sap_type: 'sap_hana'
      sap_storage_action: 'prepare'
    include_role: 
      name: ../roles/sap_storage
